import { onAuth, signIn, signOut, sendPasswordReset } from './auth.js';
import { subscribePlansV4, subscribeRoundsV4, subscribeThemesV4, ensureCleanHistoryReset } from './store-v4.js';
import { createRoundControllerV4 } from './round-flow-v4.js';
import { loadSeedDataV4 } from './seed-data-v4.js';
import { roundsView, roundDetail, findingsView, themeAdmin, editRoundDialog, themeDialog, saveRoundEdit, saveThemeForm, deleteTheme, createMasterAction, findings } from './v3-core.js?v=4.0.0';

const app = document.querySelector('#app');
const toastEl = document.querySelector('#toast');

const state = {
  activeView: 'dashboard', user: null, authReady: false, seedReady: false, resetting: false, authError: '',
  seedPlan: null, themeBank: null, livePlans: [], rounds: [], themes: [], plans: [], roundController: null,
  selectedRound: null, pendingPlan: null, pendingBackdate: false, roundFilters: { period: 'all' }, findingType: '', unsubscribers: []
};

const views = [['dashboard','Dashboard'],['annual','Årsplan'],['rounds','Historikk'],['findings','Funn & oppfølging'],['themes','Temabank'],['analytics','Analyse']];
const completeStatuses = new Set(['Gjennomført','Oppfølging pågår','Lukket']);
const esc = s => String(s ?? '').replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const dn = n => String(n || 'leder').trim().split(/\s+/)[0];
const sameName = (a,b) => dn(a).toLocaleLowerCase('nb-NO') === dn(b).toLocaleLowerCase('nb-NO');
const fmt = t => t ? new Date(Number(t)).toLocaleDateString('nb-NO') : '';
const notify = (message,error=false) => { if(!toastEl)return; toastEl.textContent=message; toastEl.classList.toggle('error',error); toastEl.classList.add('show'); clearTimeout(notify.timer); notify.timer=setTimeout(()=>toastEl.classList.remove('show'),4500); };

function isoWeekNow(){ const d=new Date(),x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())),day=x.getUTCDay()||7; x.setUTCDate(x.getUTCDate()+4-day); const year=x.getUTCFullYear(),start=new Date(Date.UTC(year,0,1)); return {year,week:Math.ceil((((x-start)/86400000)+1)/7)}; }
function nav(){ return views.map(([id,label])=>`<button class="${state.activeView===id?'active':''}" data-view="${id}">${label}</button>`).join(''); }
function login(){ return `<div class="login-screen"><div class="login-card"><img class="login-opex-logo" src="./assets/opex-hub-logo.png" alt="OpEx Hub"><span class="eyebrow">LOR · Nortura Sarpsborg</span><h1>Velkommen tilbake</h1><p>Logg inn med samme bruker som i Master tiltaksliste.</p>${state.authError?`<div class="login-error">${esc(state.authError)}</div>`:''}<form id="loginForm"><label>E-post<input id="loginEmail" type="email" required></label><label>Passord<input id="loginPassword" type="password" required></label><button class="primary-action full-action">Logg inn</button><button class="text-action" type="button" id="forgotPassword">Glemt passord?</button></form></div></div>`; }

function seedPlans(){ const year=Number(state.seedPlan?.year||2026); return (state.seedPlan?.records||[]).map((row,index)=>({id:`seed-${year}-${row.week}-${index}`,sourceSeedId:`seed-${year}-${row.week}-${index}`,year,week:Number(row.week),leaderName:row.ownerName||'',ownerName:row.ownerName||'',theme:row.themeName||'',themeName:row.themeName||'',department:row.department||'',plannedDate:'',status:row.status||'planned',source:'seed',aliases:[`seed-${year}-${row.week}-${index}`]})).filter(row=>Number.isFinite(row.week)); }

function canonicalPlans(){
  const seeds=seedPlans(),seedMap=new Map(seeds.map(row=>[row.id,row])),grouped=new Map(),standalone=[];
  for(const raw of state.livePlans||[]){
    const row={...raw,year:Number(raw.year||2026),week:Number(raw.week),leaderName:raw.leaderName||raw.ownerName||'',ownerName:raw.leaderName||raw.ownerName||'',theme:raw.theme||raw.themeName||'',themeName:raw.theme||raw.themeName||'',source:'live'};
    if(row.sourceSeedId&&seedMap.has(row.sourceSeedId)){ if(!grouped.has(row.sourceSeedId))grouped.set(row.sourceSeedId,[]); grouped.get(row.sourceSeedId).push(row); }
    else if(Number.isFinite(row.week)) standalone.push({...row,aliases:[row.id]});
  }
  const rows=seeds.map(seed=>{ const group=(grouped.get(seed.id)||[]).sort((a,b)=>Number(b.updatedAt||b.completedAt||0)-Number(a.updatedAt||a.completedAt||0)); if(!group.length)return seed; const latest=group[0]; return {...seed,...latest,id:latest.id,sourceSeedId:seed.id,year:seed.year,week:seed.week,aliases:[seed.id,...group.map(item=>item.id)]}; });
  rows.push(...standalone);
  return rows.filter(row=>!row.archived).sort((a,b)=>Number(a.week)-Number(b.week));
}

function roundCompletesPlan(round,plan){ if(!completeStatuses.has(round.status))return false; const aliases=new Set([plan.id,plan.sourceSeedId,...(plan.aliases||[])].filter(Boolean).map(String)); return aliases.has(String(round.planId||''))||aliases.has(String(round.sourceSeedId||'')); }
function done(plan){ return state.rounds.some(round=>roundCompletesPlan(round,plan)); }
function usablePlans(){ return state.plans.filter(plan=>plan.status!=='needsReview'&&plan.theme&&plan.leaderName); }
function personalPlans(){ return usablePlans().filter(plan=>sameName(plan.leaderName||plan.ownerName,state.user?.name)); }
function nextPlan(personal=false){ const now=isoWeekNow(),rows=(personal?personalPlans():usablePlans()).filter(plan=>!done(plan)); return rows.sort((a,b)=>{const af=Number(a.year)>now.year||(Number(a.year)===now.year&&Number(a.week)>=now.week)?0:1,bf=Number(b.year)>now.year||(Number(b.year)===now.year&&Number(b.week)>=now.week)?0:1; return af-bf||Number(a.year)-Number(b.year)||Number(a.week)-Number(b.week);})[0]||null; }

function stats(){
  const nowYear=new Date().getFullYear();
  const currentRounds=state.rounds.filter(round=>Number(round.planYear||new Date(Number(round.completedAt||round.startedAt||0)).getFullYear())===nowYear);
  const plan=personalPlans(),completedPlans=plan.filter(done).length,fs=findings(currentRounds);
  return {rate:plan.length?Math.round(completedPlans/plan.length*100):0,completedPlans,totalPlans:plan.length,completedRounds:currentRounds.filter(round=>completeStatuses.has(round.status)).length,open:currentRounds.filter(round=>round.status==='Oppfølging pågår').length,improvements:fs.filter(item=>item.type==='Forbedringspunkt').length,deviations:fs.filter(item=>item.type==='Avvik').length};
}

const kpi=(label,value,hint,filter,tone='')=>`<button class="card kpi interactive-kpi ${tone}" ${filter?`data-kpi-filter="${filter}"`:''}><span>${label}</span><strong>${value}</strong><small>${hint||''}</small><i>Se detaljer →</i></button>`;
function recent(){ const rows=state.rounds.slice(0,7); return `<div class="round-list">${rows.map(round=>`<button class="round-row interactive-row" data-round-open="${esc(round.id)}"><div><strong>${esc(round.theme||'LOR')}</strong><span>${esc(round.department||'')} · ${esc(round.leaderName||'')}${round.backdated?' · tilbakeført':''}</span></div><div class="round-row-end"><span>${esc(round.roundDate||fmt(round.completedAt))}</span><span class="status-pill">${esc(round.status||'Pågår')}</span><b>→</b></div></button>`).join('')||'<div class="empty-state">Ingen registrerte LOR-runder.</div>'}</div>`; }

function dashboard(){ const s=stats(),next=nextPlan(false); return `<section class="hero dashboard-hero"><div><span class="eyebrow">OpEx · Lederoppfølging 2026</span><h1>God dag, ${esc(dn(state.user.name))}</h1><p>Én datakilde for årsplan, historikk og dashboard.</p></div><div style="display:flex;gap:10px;flex-wrap:wrap"><button class="secondary-action" data-start-backdated>+ Registrer tilbake i tid</button><button class="primary-action" data-view="round">+ Start LOR</button></div></section><section class="kpi-grid dashboard-kpis">${kpi('Plan gjennomført',`${s.rate} %`,`${s.completedPlans} av ${s.totalPlans} planlagte`,'rounds','kpi-primary')}${kpi('Gjennomførte runder',s.completedRounds,'registrert i Firebase','rounds')}${kpi('Åpne oppfølginger',s.open,'krever handling','Medarbeiderinnspill','kpi-warning')}${kpi('Forbedringspunkter',s.improvements,'fra registrerte runder','Forbedringspunkt')}${kpi('Registrerte avvik',s.deviations,'fra registrerte runder','Avvik','kpi-danger')}</section><section class="grid-2 dashboard-grid"><article class="card panel"><div class="panel-head"><div><span class="eyebrow">Historikk</span><h2>Siste runder</h2></div><button class="text-action" data-view="rounds">Se alle →</button></div>${recent()}</article><article class="card panel premium-next"><span class="eyebrow">Neste oppgave</span><h2>${next?`Uke ${next.week} · ${esc(next.theme||next.themeName)}`:'Ingen planlagt runde'}</h2>${next?`<p>${esc(next.department||'')} · ${esc(next.leaderName||'Ikke fordelt')}</p><button class="primary-action full-action" data-start-plan="${esc(next.id)}">Start planlagt LOR →</button>`:''}<div class="insight"><strong>★ LOR-prinsipp</strong><br>Start positivt, vær konkret og bruk funn til læring og forbedring.</div></article></section>`; }

function planStatus(plan){ if(done(plan))return{key:'done',label:'Gjennomført'}; if(plan.status==='needsReview'||!plan.theme||!plan.leaderName)return{key:'review',label:'Må avklares'}; const now=isoWeekNow(); if(Number(plan.year)<now.year||(Number(plan.year)===now.year&&Number(plan.week)<now.week))return{key:'overdue',label:'Forfalt'}; if(Number(plan.year)===now.year&&Number(plan.week)===now.week)return{key:'current',label:'Denne uken'}; return{key:'planned',label:'Planlagt'}; }
function annual(){ const rows=state.plans,counts=rows.reduce((acc,row)=>{const key=planStatus(row).key;acc[key]=(acc[key]||0)+1;return acc;},{}); return `<section class="hero"><div><span class="eyebrow">Årsplan · 2026</span><h1>Årsplan</h1><p>Planen er statisk grunnlag. Gjennomføring hentes kun fra registrerte V4-runder.</p></div><button class="secondary-action" data-start-backdated>+ Registrer LOR tilbake i tid</button></section><section class="kpi-grid">${kpi('Gjennomført',counts.done||0,'koblet til årsplan')}${kpi('Forfalt',counts.overdue||0,'ikke gjennomført','','kpi-danger')}${kpi('Denne uken',counts.current||0,'planlagt nå')}${kpi('Planlagt',counts.planned||0,'kommende')}</section><section class="card panel"><div class="v36-head"><span>Uke</span><span>Ansvarlig</span><span>Tema</span><span>Avdeling</span><span>Status</span><span></span></div>${rows.map(row=>{const st=planStatus(row);return `<button class="v36-row ${st.key}" ${row.theme&&row.leaderName?`data-start-plan="${esc(row.id)}"`:'disabled'}><strong>Uke ${row.week}</strong><span>${esc(row.leaderName||'Ikke fordelt')}</span><span>${esc(row.theme||'Tema mangler')}</span><span>${esc(row.department||'Avdeling mangler')}</span><em class="v36-status ${st.key}">${st.label}</em><b>${st.key==='done'?'✓':'→'}</b></button>`;}).join('')}</section>`; }

function analytics(){ const fs=findings(state.rounds),by={}; fs.forEach(item=>by[item.round.theme]=(by[item.round.theme]||0)+1); const top=Object.entries(by).sort((a,b)=>b[1]-a[1]); return `<section class="hero"><div><span class="eyebrow">Ledelsesinnsikt</span><h1>Analyse</h1><p>Kun basert på V4-runder i Firebase.</p></div></section><section class="grid-2"><article class="card panel"><h2>Funn per tema</h2>${top.map(([name,count])=>`<div class="analysis-bar"><span>${esc(name)}</span><b>${count}</b><div style="--w:${Math.min(100,count*15)}%"></div></div>`).join('')||'<div class="empty-state">Mer data trengs.</div>'}</article><article class="card panel"><h2>Datagrunnlag</h2><div class="insight"><strong>${state.rounds.length} registrerte V4-runder</strong><br>Ingen importert historikk inngår i tallene.</div></article></section>`; }

function current(){ if(state.selectedRound)return roundDetail(state.selectedRound); if(state.activeView==='dashboard')return dashboard(); if(state.activeView==='annual')return annual(); if(state.activeView==='rounds')return roundsView(state.rounds,state.roundFilters); if(state.activeView==='findings')return findingsView(state.rounds,state.findingType); if(state.activeView==='themes')return themeAdmin(state.themes); if(state.activeView==='analytics')return analytics(); if(state.activeView==='round'){ if(!state.roundController){const initial=state.pendingPlan||(state.pendingBackdate?null:nextPlan(true)),backdateMode=state.pendingBackdate;state.pendingPlan=null;state.pendingBackdate=false;state.roundController=createRoundControllerV4({user:state.user,notify,themeBank:state.themeBank,initialPlan:initial,backdateMode,onDone:()=>{state.roundController=null;state.activeView='dashboard';render();}});} return state.roundController.render(); } return dashboard(); }
function shell(){ return `<div class="app-shell"><header class="topbar"><div class="topbar-inner"><button class="brand brand-button" data-view="dashboard"><img class="brand-logo" src="./lor-shield-v385.svg" alt="OpEx LOR"><div><strong>OpEx · LOR</strong><span>Lederoppfølging · Sarpsborg</span></div></button><nav class="nav">${nav()}</nav><div class="user-menu"><div class="user-avatar">${esc(dn(state.user.name)[0]||'L')}</div><span>${esc(dn(state.user.name))}</span><button id="logoutButton">Logg ut</button></div></div></header><main class="main">${current()}</main></div>`; }
function render(){ if(!state.authReady||!state.seedReady||state.resetting){app.innerHTML=`<div class="loading-screen">${state.resetting?'Rydder gammel LOR-historikk…':'Laster LOR…'}</div>`;return;} app.innerHTML=state.user?shell():login(); }
function rebuild(){ state.plans=canonicalPlans(); if(state.selectedRound)state.selectedRound=state.rounds.find(round=>round.id===state.selectedRound.id)||null; render(); }
function disconnect(){ state.unsubscribers.forEach(fn=>fn?.()); state.unsubscribers=[]; }
function connect(){ disconnect(); if(!state.user)return; state.unsubscribers.push(subscribePlansV4(rows=>{state.livePlans=rows;rebuild();})); state.unsubscribers.push(subscribeRoundsV4(rows=>{state.rounds=rows;rebuild();})); state.unsubscribers.push(subscribeThemesV4(rows=>{state.themes=rows.filter(theme=>theme.active!==false);render();})); }

app.addEventListener('click',async event=>{
  const closer=event.target.closest('[data-dialog-close]'); if(closer){closer.closest('dialog')?.remove();return;}
  const backdated=event.target.closest('[data-start-backdated]'); if(backdated){state.pendingPlan=null;state.pendingBackdate=true;state.selectedRound=null;state.roundController=null;state.activeView='round';render();return;}
  const startPlan=event.target.closest('[data-start-plan]'); if(startPlan){const plan=state.plans.find(row=>String(row.id)===String(startPlan.dataset.startPlan));if(!plan)return;if(done(plan)){notify('Denne planrunden er allerede gjennomført.');return;}state.pendingPlan=plan;state.pendingBackdate=Number(plan.week)<isoWeekNow().week;state.selectedRound=null;state.roundController=null;state.activeView='round';render();return;}
  const view=event.target.closest('[data-view]'); if(view){state.selectedRound=null;state.activeView=view.dataset.view;if(state.activeView!=='round')state.roundController=null;render();return;}
  const openRound=event.target.closest('[data-round-open]'); if(openRound){state.selectedRound=state.rounds.find(round=>round.id===openRound.dataset.roundOpen)||null;render();return;}
  const edit=event.target.closest('[data-round-edit]'); if(edit){const round=state.rounds.find(item=>item.id===edit.dataset.roundEdit);if(!round)return;document.body.insertAdjacentHTML('beforeend',editRoundDialog(round));return;}
  const k=event.target.closest('[data-kpi-filter]'); if(k){const filter=k.dataset.kpiFilter;if(filter==='rounds')state.activeView='rounds';else{state.activeView='findings';state.findingType=filter;}state.selectedRound=null;render();return;}
  const findingType=event.target.closest('[data-find-type]'); if(findingType){state.findingType=findingType.dataset.findType;render();return;}
  if(event.target.closest('[data-theme-new]')){document.body.insertAdjacentHTML('beforeend',themeDialog());return;}
  const themeEdit=event.target.closest('[data-theme-edit]'); if(themeEdit){const custom=state.themes.find(theme=>theme.id===themeEdit.dataset.themeEdit||theme.name===themeEdit.dataset.themeName);document.body.insertAdjacentHTML('beforeend',themeDialog(custom||{id:themeEdit.dataset.themeEdit}));return;}
  const themeDisable=event.target.closest('[data-theme-disable]'); if(themeDisable&&confirm('Deaktivere temaet?')){await deleteTheme(themeDisable.dataset.themeDisable);notify('Tema deaktivert.');return;}
  const masterAction=event.target.closest('[data-master-action]'); if(masterAction){const finding=findings(state.rounds).find(item=>item.id===masterAction.dataset.masterAction);if(!finding)return;const title=prompt('Tiltakstittel',finding.text);if(!title)return;const description=prompt('Beskrivelse / ønsket effekt',`Opprettet fra LOR: ${finding.round.theme} – ${finding.round.department}`)||'';try{const id=await createMasterAction({round:finding.round,finding:finding.text,findingId:finding.id,user:state.user,title,description});notify(`Tiltak opprettet i Master ✓ (${id.slice(-6)})`);}catch(error){console.error(error);notify('Kunne ikke opprette tiltak i Master.',true);}return;}
  if(event.target.closest('#logoutButton')){await signOut();return;}
  if(event.target.closest('#forgotPassword')){const mail=document.querySelector('#loginEmail')?.value?.trim();if(!mail)return notify('Skriv inn e-post først.',true);await sendPasswordReset(mail);notify('E-post sendt.');return;}
  if(state.activeView==='round'&&state.roundController){try{const result=await state.roundController.handle(event.target,app);if(result?.rerender)render();}catch(error){console.error(error);notify(error?.message||'Kunne ikke lagre. Prøv igjen.',true);}}
});

app.addEventListener('change',event=>{const filter=event.target.closest('[data-lor-filter]');if(filter){state.roundFilters[filter.dataset.lorFilter]=filter.value;render();return;}if(event.target.id==='interviewAnonymous'){const wrap=document.querySelector('#employeeNameWrap');if(wrap)wrap.hidden=event.target.checked;}if(state.activeView==='round'&&state.roundController?.handleChange(event.target))render();});
app.addEventListener('submit',async event=>{if(event.target.id==='loginForm'){event.preventDefault();try{await signIn(document.querySelector('#loginEmail').value,document.querySelector('#loginPassword').value);}catch(error){state.authError=error.friendlyMessage||'Innlogging mislyktes';render();}return;}if(event.target.matches('[data-round-edit-form]')){event.preventDefault();const round=state.rounds.find(item=>item.id===event.target.dataset.roundEditForm);await saveRoundEdit(event.target,round,state.user);event.target.closest('dialog')?.remove();notify('LOR oppdatert.');return;}if(event.target.matches('[data-theme-form]')){event.preventDefault();const old=state.themes.find(item=>item.id===event.target.dataset.themeForm);await saveThemeForm(event.target,old);event.target.closest('dialog')?.remove();notify('Temabank oppdatert.');}});

loadSeedDataV4().then(seed=>{state.seedPlan=seed.plan2026;state.themeBank=seed.themeBank;state.seedReady=true;state.plans=canonicalPlans();render();}).catch(error=>{console.error(error);state.seedReady=true;render();});
onAuth(async user=>{disconnect();state.user=user;state.authReady=true;state.selectedRound=null;state.roundController=null;if(!user){state.rounds=[];state.livePlans=[];state.plans=canonicalPlans();render();return;}state.resetting=true;render();try{const reset=await ensureCleanHistoryReset();if(reset)notify('Gammel LOR-historikk er fjernet. V4 starter med blank historikk ✓');}catch(error){console.error('[LOR V4 reset]',error);notify('Kunne ikke fullføre V4-reset. Ingen nye registreringer bør gjøres før dette er løst.',true);}finally{state.resetting=false;}connect();render();});
window.__lorV4={state,rebuild};
