import { onAuth, signIn, signOut, sendPasswordReset } from './auth.js';
import { subscribePlannedRounds, subscribeRounds, subscribeThemes } from './store.js';
import { createRoundController } from './round-flow.js';
import { loadSeedData, planForUser } from './seed-data.js';
import { roundsView,roundDetail,findingsView,themeAdmin,editRoundDialog,themeDialog,saveRoundEdit,saveThemeForm,deleteTheme,createMasterAction,findings } from './v3-core.js';
const app=document.querySelector('#app'),toastEl=document.querySelector('#toast');
const state={activeView:'dashboard',user:null,authReady:false,authError:'',plans:[],livePlans:[],rounds:[],liveRounds:[],themes:[],roundController:null,unsubscribers:[],seedReady:false,seedPlan:null,themeBank:null,legacyHistory:[],roundFilters:{},findingType:'',selectedRound:null};
const views=[['dashboard','Dashboard'],['rounds','LOR-runder'],['findings','Funn & oppfølging'],['themes','Temabank'],['analytics','Analyse']];
const notify=(m,e=false)=>{toastEl.textContent=m;toastEl.classList.toggle('error',e);toastEl.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(()=>toastEl.classList.remove('show'),3500)};
const dn=n=>String(n||'leder').trim().split(/\s+/)[0];
const fmt=t=>t?new Date(Number(t)).toLocaleDateString('nb-NO'):'';
const nav=()=>views.map(([id,l])=>`<button class="${state.activeView===id?'active':''}" data-view="${id}">${l}</button>`).join('');
function login(){return `<div class="login-screen"><div class="login-card"><div class="login-mark">LOR</div><span class="eyebrow">OpEx · Nortura Sarpsborg</span><h1>Velkommen tilbake</h1><p>Logg inn med samme bruker som i Master tiltaksliste.</p>${state.authError?`<div class="login-error">${state.authError}</div>`:''}<form id="loginForm"><label>E-post<input id="loginEmail" type="email" required></label><label>Passord<input id="loginPassword" type="password" required></label><button class="primary-action full-action">Logg inn</button><button class="text-action" type="button" id="forgotPassword">Glemt passord?</button></form></div></div>`}
function legacy(row){return {id:`legacy-${row.year||row.date}-${row.week}-${row.leader}`,theme:row.theme,department:row.department,leaderName:row.leader,status:row.date?'Gjennomført':'Ikke registrert',completedAt:row.date?new Date(`${row.date}T12:00:00`).getTime():null,startedAt:row.date?new Date(`${row.date}T12:00:00`).getTime():null,summary:{counts:{deviation:row.ok===false?1:0}},legacy:true}}
function week(){const d=new Date(),x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())),day=x.getUTCDay()||7;x.setUTCDate(x.getUTCDate()+4-day);const s=new Date(Date.UTC(x.getUTCFullYear(),0,1));return Math.ceil((((x-s)/86400000)+1)/7)}
const done=p=>state.liveRounds.some(r=>r.planId===p.id||(r.planWeek&&Number(r.planWeek)===Number(p.week)&&r.theme===(p.theme||p.themeName)&&r.leaderUid===state.user?.uid));
const usable=()=>state.plans.filter(p=>p.status!=='needsReview');
function nextPlan(){const w=week();return usable().filter(p=>!done(p)).sort((a,b)=>{const af=Number(a.week)>=w?0:1,bf=Number(b.week)>=w?0:1;return af-bf||Number(a.week)-Number(b.week)})[0]||null}
function stats(){const y=new Date().getFullYear(),live=state.liveRounds.filter(r=>{const t=Number(r.startedAt||r.completedAt||0);return !t||new Date(t).getFullYear()===y}),plan=usable(),pc=plan.filter(done).length,fs=findings(live);return {rate:plan.length?Math.round(pc/plan.length*100):0,pc,pt:plan.length,completed:live.filter(r=>['Gjennomført','Oppfølging pågår','Lukket'].includes(r.status)).length,open:live.filter(r=>r.status==='Oppfølging pågår').length,imp:fs.filter(x=>x.type==='Forbedringspunkt').length,dev:fs.filter(x=>x.type==='Avvik').length}}
const kpi=(label,value,hint,filter,tone='')=>`<button class="card kpi interactive-kpi ${tone}" ${filter?`data-kpi-filter="${filter}"`:''}><span>${label}</span><strong>${value}</strong><small>${hint||''}</small><i>Se detaljer →</i></button>`;
function recent(){return `<div class="round-list">${state.rounds.slice(0,7).map(r=>`<button class="round-row interactive-row" data-round-open="${r.id}"><div><strong>${r.theme||'LOR'}</strong><span>${r.department||''} · ${r.leaderName||''}${r.legacy?' · historikk':''}</span></div><div class="round-row-end"><span>${fmt(r.completedAt)}</span><span class="status-pill">${r.status||'Pågår'}</span><b>→</b></div></button>`).join('')||'<div class="empty-state">Ingen runder.</div>'}</div>`}
function dashboard(){const s=stats(),n=nextPlan();return `<section class="hero dashboard-hero"><div><span class="eyebrow">OpEx · Lederoppfølging 2026</span><h1>God dag, ${dn(state.user.name)}</h1><p>Fra observasjon til forbedring – én samlet arbeidsflate.</p></div><button class="primary-action" data-view="round">+ Start LOR</button></section><section class="kpi-grid dashboard-kpis">${kpi('Plan gjennomført',`${s.rate} %`,`${s.pc} av ${s.pt} planlagte`,'rounds','kpi-primary')}${kpi('Gjennomførte runder',s.completed,'registrert i appen','rounds')}${kpi('Åpne oppfølginger',s.open,'krever handling','Medarbeiderinnspill','kpi-warning')}${kpi('Forbedringspunkter',s.imp,'fra digitale runder','Forbedringspunkt')}${kpi('Registrerte avvik',s.dev,'fra digitale runder','Avvik','kpi-danger')}</section><section class="grid-2 dashboard-grid"><article class="card panel"><div class="panel-head"><div><span class="eyebrow">Felles historikk</span><h2>Siste runder</h2></div><button class="text-action" data-view="rounds">Se alle →</button></div>${recent()}</article><article class="card panel premium-next"><span class="eyebrow">Neste oppgave</span><h2>${n?`Uke ${n.week} · ${n.theme||n.themeName}`:'Ingen planlagt runde'}</h2>${n?`<p>${n.department||''} · planlagt for ${dn(state.user.name)}</p><button class="primary-action full-action" data-view="round">Start planlagt LOR →</button>`:''}<div class="insight"><strong>${n?.principle||'★ LOR-prinsipp'}</strong><br>${n?.guidance||'Start positivt, vær konkret og bruk funn til læring og forbedring.'}</div></article></section>`}
function analytics(){const fs=findings(state.liveRounds);const by={};fs.forEach(x=>by[x.round.theme]=(by[x.round.theme]||0)+1);const top=Object.entries(by).sort((a,b)=>b[1]-a[1]);return `<section class="hero"><div><span class="eyebrow">Ledelsesinnsikt</span><h1>Analyse</h1><p>Utvikling basert på reelle LOR-data.</p></div></section><section class="grid-2"><article class="card panel"><h2>Funn per tema</h2>${top.map(([n,c])=>`<div class="analysis-bar"><span>${n}</span><b>${c}</b><div style="--w:${Math.min(100,c*15)}%"></div></div>`).join('')||'<div class="empty-state">Mer data trengs.</div>'}</article><article class="card panel"><h2>Veien videre</h2><div class="insight"><strong>Prioriter gjentakelser</strong><br>Temaer med flere funn bør vurderes for målrettet oppfølging, temajustering eller tiltak i Master.</div></article></section>`}
function current(){if(state.selectedRound)return roundDetail(state.selectedRound);if(state.activeView==='dashboard')return dashboard();if(state.activeView==='rounds')return roundsView(state.rounds,state.roundFilters);if(state.activeView==='findings')return findingsView(state.liveRounds,state.findingType);if(state.activeView==='themes')return themeAdmin(state.themes);if(state.activeView==='analytics')return analytics();if(state.activeView==='round'){if(!state.roundController)state.roundController=createRoundController({user:state.user,notify,themeBank:state.themeBank,initialPlan:nextPlan(),onDone:()=>{state.roundController=null;state.activeView='dashboard';render()}});return state.roundController.render()}return dashboard()}
function shell(){return `<div class="app-shell"><header class="topbar"><div class="topbar-inner"><button class="brand brand-button" data-view="dashboard"><div class="opex-mark">O</div><div><strong>OpEx · LOR</strong><span>Lederoppfølging · Sarpsborg</span></div></button><nav class="nav">${nav()}</nav><div class="user-menu"><div class="user-avatar">${dn(state.user.name)[0]}</div><span>${dn(state.user.name)}</span><button id="logoutButton">Logg ut</button></div></div></header><main class="main">${current()}</main></div>`}
function render(){if(!state.authReady||!state.seedReady){app.innerHTML='<div class="loading-screen">Laster LOR…</div>';return}app.innerHTML=state.user?shell():login()}
function rebuild(){state.plans=state.livePlans.length?state.livePlans:planForUser(state.seedPlan,state.user?.name).map((r,i)=>({id:`seed-${r.week}-${i}`,...r,theme:r.themeName}));state.rounds=[...state.liveRounds,...state.legacyHistory.map(legacy)].sort((a,b)=>Number(b.startedAt||0)-Number(a.startedAt||0));if(state.selectedRound)state.selectedRound=state.rounds.find(r=>r.id===state.selectedRound.id)||null;render()}
function connect(){state.unsubscribers.forEach(f=>f?.());state.unsubscribers=[];if(!state.user)return;state.unsubscribers.push(subscribePlannedRounds(state.user.uid,x=>{state.livePlans=x;rebuild()}));state.unsubscribers.push(subscribeRounds(x=>{state.liveRounds=x;rebuild()}));state.unsubscribers.push(subscribeThemes(x=>{state.themes=x.filter(t=>t.active!==false);render()}))}
app.addEventListener('click',async e=>{const v=e.target.closest('[data-view]');if(v){state.selectedRound=null;state.activeView=v.dataset.view;if(state.activeView!=='round')state.roundController=null;render();return}const ro=e.target.closest('[data-round-open]');if(ro){state.selectedRound=state.rounds.find(r=>r.id===ro.dataset.roundOpen);render();return}const edit=e.target.closest('[data-round-edit]');if(edit){const r=state.rounds.find(x=>x.id===edit.dataset.roundEdit);if(r?.legacy)return notify('Importert historikk er skrivebeskyttet.',true);document.body.insertAdjacentHTML('beforeend',editRoundDialog(r));return}const k=e.target.closest('[data-kpi-filter]');if(k){const f=k.dataset.kpiFilter;if(f==='rounds'){state.activeView='rounds'}else{state.activeView='findings';state.findingType=f}state.selectedRound=null;render();return}const ft=e.target.closest('[data-find-type]');if(ft){state.findingType=ft.dataset.findType;render();return}if(e.target.closest('[data-theme-new]')){document.body.insertAdjacentHTML('beforeend',themeDialog());return}const te=e.target.closest('[data-theme-edit]');if(te){document.body.insertAdjacentHTML('beforeend',themeDialog(state.themes.find(t=>t.id===te.dataset.themeEdit)));return}const td=e.target.closest('[data-theme-disable]');if(td&&confirm('Deaktivere temaet?')){await deleteTheme(td.dataset.themeDisable);notify('Tema deaktivert.');return}const ma=e.target.closest('[data-master-action]');if(ma){const f=findings(state.liveRounds).find(x=>x.id===ma.dataset.masterAction);if(!f)return;const title=prompt('Tiltakstittel',f.text);if(!title)return;const description=prompt('Beskrivelse / ønsket effekt',`Opprettet fra LOR: ${f.round.theme} – ${f.round.department}`)||'';try{await createMasterAction({round:f.round,finding:f.text,user:state.user,title,description});notify('Tiltak opprettet i Master tiltaksliste.')}catch(err){console.error(err);notify('Kunne ikke opprette tiltak i Master. Kontroller Firebase-reglene.',true)}return}if(e.target.closest('#logoutButton'))return signOut();if(e.target.closest('#forgotPassword')){const mail=document.querySelector('#loginEmail')?.value?.trim();if(!mail)return notify('Skriv inn e-post først.',true);await sendPasswordReset(mail);notify('E-post sendt.');return}if(state.activeView==='round'&&state.roundController){try{const x=await state.roundController.handle(e.target,app);if(x?.rerender)render()}catch(err){console.error(err);notify('Kunne ikke lagre. Prøv igjen.',true)}}});
app.addEventListener('change',e=>{const f=e.target.closest('[data-lor-filter]');if(f){state.roundFilters[f.dataset.lorFilter]=f.value;render();return}if(e.target.id==='interviewAnonymous'){const w=document.querySelector('#employeeNameWrap');if(w)w.hidden=e.target.checked}if(state.activeView==='round'&&state.roundController?.handleChange(e.target))render()});
app.addEventListener('submit',async e=>{if(e.target.id==='loginForm'){e.preventDefault();try{await signIn(document.querySelector('#loginEmail').value,document.querySelector('#loginPassword').value)}catch(err){state.authError=err.friendlyMessage||'Innlogging mislyktes';render()}return}if(e.target.matches('[data-round-edit-form]')){e.preventDefault();if(e.submitter?.value!=='save'){e.target.closest('dialog').remove();return}const r=state.rounds.find(x=>x.id===e.target.dataset.roundEditForm);await saveRoundEdit(e.target,r,state.user);e.target.closest('dialog').remove();notify('LOR oppdatert med sporbar endring.');return}if(e.target.matches('[data-theme-form]')){e.preventDefault();if(e.submitter?.value!=='save'){e.target.closest('dialog').remove();return}const old=state.themes.find(x=>x.id===e.target.dataset.themeForm);await saveThemeForm(e.target,old);e.target.closest('dialog').remove();notify('Temabank oppdatert.')}});
loadSeedData().then(seed=>{state.seedPlan=seed.plan2026;state.themeBank=seed.themeBank;state.legacyHistory=seed.legacyHistory;state.seedReady=true;if(state.user)connect();render()}).catch(err=>{console.error(err);state.seedReady=true;render()});
onAuth(user=>{state.user=user;state.authReady=true;state.selectedRound=null;if(user)connect();else{state.unsubscribers.forEach(f=>f?.());state.unsubscribers=[]}render()});
