import { updateRound, saveTheme, deleteTheme, createMasterAction } from './store.js';

const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const prettyLeader=n=>{const s=String(n||'').trim();if(!s)return 'Ukjent leder';if(s.includes('.'))return s.split('.')[0].replace(/^./,c=>c.toUpperCase());return s;};
const statusLabel=s=>({ok:'OK',improvement:'Forbedringspunkt',deviation:'Avvik',na:'Ikke relevant',note:'Notat',positive:'Positiv'}[s]||s||'');
const bank=await fetch('./data/seed/themes-v1.json',{cache:'no-store'}).then(r=>r.ok?r.json():{}).catch(()=>({}));
const imported=[...(bank.sharedThemes||[]),...(bank.departmentThemes||[])].map(t=>({...t,source:'imported',questions:(t.questions||Object.values(t.variants||{})[0]||[]).map((q,i)=>typeof q==='string'?{id:`${t.id||'theme'}-q${i+1}`,text:q}:q)}));
function themeFor(round){return imported.find(t=>t.name===round.theme)||null;}
function questionText(round,id,x){if(x.question||x.questionText)return x.question||x.questionText;const t=themeFor(round);return t?.questions?.find(q=>q.id===id)?.text||`Kontrollpunkt ${id.replace(/^.*q/i,'')||''}`;}

export function findings(rounds=[]){const out=[];for(const r of rounds){for(const [id,x] of Object.entries(r.responses||{})){const raw=x.status||x.result||x.answer;const type=raw==='improvement'?'Forbedringspunkt':raw==='deviation'?'Avvik':raw;if(['Forbedringspunkt','Avvik'].includes(type))out.push({id:`${r.id}:${id}`,round:r,type,text:x.comment||x.text||questionText(r,id,x)||type});}for(const [id,x] of Object.entries(r.employeeInterviews||{})){if(x.needsFollowUp||x.requiresFollowUp||x.followUp)out.push({id:`${r.id}:i:${id}`,round:r,type:'Medarbeiderinnspill',text:x.improvement||x.improve||x.comment||'Medarbeiderinnspill'});} }return out;}

export function roundsView(rounds=[],filters={}){const live=rounds.filter(r=>!r.legacy),leaders=[...new Set(live.map(r=>r.leaderName).filter(Boolean))],deps=[...new Set(rounds.map(r=>r.department).filter(Boolean))],themes=[...new Set(rounds.map(r=>r.theme).filter(Boolean))];const f=rounds.filter(r=>(!filters.leader||r.leaderName===filters.leader)&&(!filters.department||r.department===filters.department)&&(!filters.theme||r.theme===filters.theme));const opts=(a,s,all,pretty=false)=>`<option value="">${all}</option>${a.map(x=>`<option value="${esc(x)}" ${x===s?'selected':''}>${esc(pretty?prettyLeader(x):x)}</option>`).join('')}`;return `<section class="hero"><div><span class="eyebrow">Felles historikk</span><h1>Alle LOR-runder</h1><p>Alle godkjente brukere ser samme historikk.</p></div></section><div class="filterbar labeled-filters"><label><span>Leder</span><select data-lor-filter="leader">${opts(leaders,filters.leader,'Alle aktive ledere',true)}</select></label><label><span>Avdeling</span><select data-lor-filter="department">${opts(deps,filters.department,'Alle avdelinger')}</select></label><label><span>Tema</span><select data-lor-filter="theme">${opts(themes,filters.theme,'Alle temaer')}</select></label></div><section class="card panel"><div class="round-list">${f.length?f.map(r=>`<button class="round-row interactive-row" data-round-open="${r.id}"><div><strong>${esc(r.theme||'LOR')}</strong><span>${esc(r.department)} · ${esc(prettyLeader(r.leaderName))}${r.legacy?' · importert historikk':''}</span></div><div class="round-row-end"><span>${r.completedAt?new Date(Number(r.completedAt)).toLocaleDateString('nb-NO'):''}</span><span class="status-pill">${esc(r.status||'Pågår')}</span><b>→</b></div></button>`).join(''):'<div class="empty-state">Ingen runder matcher filtrene.</div>'}</div></section>`;}

export function roundDetail(r){const responses=Object.entries(r.responses||{}),interviews=Object.values(r.employeeInterviews||{});return `<section class="detail-top"><button class="back-action" data-view="rounds">← Tilbake til LOR-runder</button></section><section class="hero"><div><span class="eyebrow">LOR-detalj</span><h1>${esc(r.theme||'LOR')}</h1><p>${esc(r.department)} · ${esc(prettyLeader(r.leaderName))} · ${esc(r.status)}</p></div>${r.legacy?'':`<button class="secondary-action" data-round-edit="${r.id}">Rediger hele runden</button>`}</section><section class="grid-2 detail-grid"><article class="card panel"><h2>Kontrollpunkter</h2>${responses.length?responses.map(([id,x])=>`<div class="detail-item"><div class="detail-item-head"><b>${esc(questionText(r,id,x))}</b><span class="answer-badge">${esc(statusLabel(x.status||x.result||x.answer))}</span></div>${x.comment||x.text?`<p>${esc(x.comment||x.text)}</p>`:''}${x.positive?`<small>★ Positiv observasjon: ${esc(x.positive)}</small>`:''}</div>`).join(''):'<div class="empty-state">Ingen detaljer lagret.</div>'}</article><article class="card panel"><h2>Medarbeiderdialog</h2>${interviews.length?interviews.map(x=>`<div class="detail-item"><b>${x.anonymous!==false?'Anonym medarbeider':esc(x.employeeName||'Navngitt medarbeider')}</b>${x.environment||x.workEnvironment?`<p><strong>Arbeidshverdag:</strong> ${esc(x.environment||x.workEnvironment)}</p>`:''}${x.positive?`<p><strong>Det som fungerer:</strong> ${esc(x.positive)}</p>`:''}${x.improvement||x.improve?`<p><strong>Forbedring:</strong> ${esc(x.improvement||x.improve)}</p>`:''}</div>`).join(''):'<div class="empty-state">Ingen intervju registrert.</div>'}<h3>Oppsummering</h3><p>${esc(r.summary?.nextStep||r.summary?.text||'Ingen oppsummering registrert.')}</p><small>Sist endret: ${r.updatedAt?new Date(Number(r.updatedAt)).toLocaleString('nb-NO'):''}${r.lastEditedBy?` av ${esc(prettyLeader(r.lastEditedBy))}`:''}</small></article></section>`;}

export function findingsView(rounds=[],type=''){const all=findings(rounds),f=type?all.filter(x=>x.type===type):all;return `<section class="hero"><div><span class="eyebrow">Funn & oppfølging</span><h1>${type?esc(type):'Alle funn'}</h1><p>Fra funn til handling – med sporbar kobling til original LOR.</p></div></section><div class="filterbar finding-tabs"><button data-find-type="" class="${!type?'active':''}">Alle funn</button><button data-find-type="Forbedringspunkt" class="${type==='Forbedringspunkt'?'active':''}">Forbedringspunkter</button><button data-find-type="Avvik" class="${type==='Avvik'?'active':''}">Avvik</button><button data-find-type="Medarbeiderinnspill" class="${type==='Medarbeiderinnspill'?'active':''}">Medarbeiderinnspill</button></div><section class="card panel">${f.length?f.map(x=>`<div class="finding-row"><div><span class="finding-type">${esc(x.type)}</span><strong>${esc(x.text)}</strong><small>${esc(x.round.theme)} · ${esc(x.round.department)} · ${esc(prettyLeader(x.round.leaderName))}</small></div><div class="finding-actions"><button class="text-action" data-round-open="${x.round.id}">Åpne LOR</button><button class="primary-action compact" data-master-action="${esc(x.id)}">+ Tiltak i Master</button></div></div>`).join(''):'<div class="empty-state">Ingen funn i denne kategorien.</div>'}</section>`;}

function mergedThemes(custom=[]){const byName=new Map(custom.map(t=>[t.name,t]));return [...imported.map(t=>byName.get(t.name)||t),...custom.filter(t=>!imported.some(i=>i.name===t.name))];}
export function themeAdmin(themes=[]){const all=mergedThemes(themes);return `<section class="hero"><div><span class="eyebrow">Administrasjon</span><h1>Temabank</h1><p>Opprett, rediger og fas ut temaer uten kodeendringer.</p></div><button class="primary-action" data-theme-new>+ Nytt tema</button></section><section class="theme-grid">${all.map(t=>`<article class="card theme-card"><div><span class="theme-source">${t.source==='imported'?'Importert V1':'Egendefinert'}</span><h3>${esc(t.name)}</h3><p>${esc(t.principle||t.purpose||'Ingen temaspesifikk veiledning satt ennå.')}</p><small>${(t.questions||[]).length} kontrollpunkter${(t.departments||[]).length?` · ${(t.departments||[]).join(', ')}`:''}</small></div><div class="theme-actions"><button class="text-action" data-theme-edit="${esc(t.id||t.name)}" data-theme-name="${esc(t.name)}">Rediger</button>${t.source==='imported'?'':`<button class="text-action danger-text" data-theme-disable="${t.id}">Deaktiver</button>`}</div></article>`).join('')}</section>`;}

export function editRoundDialog(r){const responses=Object.entries(r.responses||{}),interviews=Object.entries(r.employeeInterviews||{});return `<dialog class="lor-dialog lor-dialog-wide" open><form method="dialog" data-round-edit-form="${r.id}"><div class="dialog-head"><div><span class="eyebrow">Full redigering</span><h2>Rediger LOR</h2></div><button value="cancel" class="dialog-close">×</button></div><div class="edit-grid"><label>Status<select name="status">${['Pågår','Gjennomført','Oppfølging pågår','Lukket'].map(s=>`<option ${s===r.status?'selected':''}>${s}</option>`).join('')}</select></label><label class="full">Oppsummering<textarea name="summary">${esc(r.summary?.nextStep||r.summary?.text||'')}</textarea></label></div><h3>Kontrollpunkter</h3><div class="edit-responses">${responses.map(([id,x])=>`<section class="edit-response" data-edit-response="${esc(id)}"><b>${esc(questionText(r,id,x))}</b><div class="edit-grid"><label>Status<select data-response-field="status">${[['ok','OK'],['improvement','Forbedringspunkt'],['deviation','Avvik'],['na','Ikke relevant'],['note','Notat']].map(([v,l])=>`<option value="${v}" ${v===(x.status||x.result||x.answer)?'selected':''}>${l}</option>`).join('')}</select></label><label class="full">Kommentar<textarea data-response-field="comment">${esc(x.comment||x.text||'')}</textarea></label><label class="full">Positiv observasjon<input data-response-field="positive" value="${esc(x.positive||'')}"></label></div></section>`).join('')}</div>${interviews.length?`<h3>Medarbeiderdialog</h3>${interviews.map(([id,x])=>`<section class="edit-response" data-edit-interview="${esc(id)}"><div class="edit-grid"><label>Arbeidshverdag<textarea data-interview-field="environment">${esc(x.environment||x.workEnvironment||'')}</textarea></label><label>Det som fungerer<textarea data-interview-field="positive">${esc(x.positive||'')}</textarea></label><label class="full">Hva bør forbedres?<textarea data-interview-field="improvement">${esc(x.improvement||x.improve||'')}</textarea></label><label class="checkbox-label"><input type="checkbox" data-interview-field="needsFollowUp" ${x.needsFollowUp||x.requiresFollowUp||x.followUp?'checked':''}> Krever oppfølging</label></div></section>`).join('')}`:''}<div class="dialog-actions sticky-dialog-actions"><button value="cancel">Avbryt</button><button class="primary-action" value="save">Lagre alle endringer</button></div></form></dialog>`;}

export function themeDialog(t={}){if(!t.name&&t.id)t=mergedThemes([]).find(x=>x.id===t.id||x.name===t.id)||t;return `<dialog class="lor-dialog" open><form method="dialog" data-theme-form="${esc(t.id||'')}"><h2>${t.name?'Rediger tema':'Nytt tema'}</h2><label>Navn<input name="name" required value="${esc(t.name)}"></label><label>Prinsipp / veiledning<textarea name="principle">${esc(t.principle||t.purpose||'')}</textarea></label><label>Avdelinger<input name="departments" value="${esc((t.departments||[]).join(', '))}" placeholder="Renhold, Ferdigmat, Rekvisita"></label><label>Kontrollpunkter – ett per linje<textarea name="questions">${esc((t.questions||[]).map(q=>typeof q==='string'?q:q.text||q.question).join('\n'))}</textarea></label><div class="dialog-actions"><button value="cancel">Avbryt</button><button class="primary-action" value="save">Lagre tema</button></div></form></dialog>`;}

export async function saveRoundEdit(form,r,user){const fd=new FormData(form),responses={...(r.responses||{})},employeeInterviews={...(r.employeeInterviews||{})};form.querySelectorAll('[data-edit-response]').forEach(w=>{const id=w.dataset.editResponse,old=responses[id]||{};responses[id]={...old,status:w.querySelector('[data-response-field="status"]').value,comment:w.querySelector('[data-response-field="comment"]').value.trim(),positive:w.querySelector('[data-response-field="positive"]').value.trim()};});form.querySelectorAll('[data-edit-interview]').forEach(w=>{const id=w.dataset.editInterview,old=employeeInterviews[id]||{};employeeInterviews[id]={...old,environment:w.querySelector('[data-interview-field="environment"]').value.trim(),positive:w.querySelector('[data-interview-field="positive"]').value.trim(),improvement:w.querySelector('[data-interview-field="improvement"]').value.trim(),needsFollowUp:w.querySelector('[data-interview-field="needsFollowUp"]').checked};});await updateRound(r.id,{status:fd.get('status'),summary:{...(r.summary||{}),nextStep:fd.get('summary')},responses,employeeInterviews},user);}
export async function saveThemeForm(form,existing){const fd=new FormData(form),qs=String(fd.get('questions')||'').split('\n').map(x=>x.trim()).filter(Boolean).map((text,i)=>({id:`q${i+1}`,text}));return saveTheme({...(existing||{}),id:form.dataset.themeForm||existing?.id||undefined,name:fd.get('name'),principle:fd.get('principle'),departments:String(fd.get('departments')||'').split(',').map(x=>x.trim()).filter(Boolean),questions:qs,active:true});}

document.addEventListener('click',e=>{if(e.target.closest('[data-round-open]'))history.pushState({lorDetail:true},'',location.href);});
window.addEventListener('popstate',()=>{document.querySelector('[data-view="rounds"]')?.click();});

export {deleteTheme,createMasterAction};
