import { db, serverTimestamp } from './firebase.js';

let seedPlan=null, livePlans=[], rounds=[], bound=false, activeYear=2026;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const first=n=>String(n||'').trim().split(/\s+/)[0]||'—';
function isoWeek(date=new Date()){const d=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate()));const day=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()+4-day);const y0=new Date(Date.UTC(d.getUTCFullYear(),0,1));return {year:d.getUTCFullYear(),week:Math.ceil((((d-y0)/86400000)+1)/7)};}
function endOfIsoWeek(year,week){const jan4=new Date(Date.UTC(year,0,4));const day=jan4.getUTCDay()||7;const monday=new Date(jan4);monday.setUTCDate(jan4.getUTCDate()-day+1+(week-1)*7);const sunday=new Date(monday);sunday.setUTCDate(monday.getUTCDate()+6);sunday.setUTCHours(23,59,59,999);return sunday.getTime();}
function rowKey(r){return `${r.year||activeYear}:${r.week}`;}
function mergedRows(year=activeYear){const seed=(seedPlan?.records||[]).map((r,i)=>({id:`seed-${year}-${r.week}-${i}`,year:seedPlan.year||2026,leaderName:r.ownerName||'',theme:r.themeName||'',department:r.department||'',status:r.status||'planned',source:'seed'})).filter(r=>r.year===year);const by=new Map(seed.map(r=>[rowKey(r),r]));livePlans.filter(r=>Number(r.year||2026)===Number(year)).forEach(r=>{const key=rowKey(r);by.set(key,{...(by.get(key)||{}),...r,source:'live'});});return [...by.values()].sort((a,b)=>Number(a.week)-Number(b.week));}
function matchRound(p){return rounds.find(r=>r.planId===p.id||(Number(r.planWeek)===Number(p.week)&&(r.theme||'')===(p.theme||'')&&(!p.department||r.department===p.department)&&(!p.leaderName||first(r.leaderName).toLowerCase()===first(p.leaderName).toLowerCase())));}
function planStatus(p){const r=matchRound(p);if(r){const done=Number(r.completedAt||r.startedAt||0);const late=done&&done>endOfIsoWeek(Number(p.year||activeYear),Number(p.week));return {key:late?'late':'done',label:late?'Gjennomført for sent':'Gjennomført'};}const now=isoWeek();const y=Number(p.year||activeYear),w=Number(p.week);if(y<now.year||(y===now.year&&w<now.week))return {key:'overdue',label:'Forfalt'};if(y===now.year&&w===now.week)return {key:'current',label:'Denne uken'};return {key:'planned',label:'Planlagt'};}
function bind(){if(bound)return;bound=true;fetch('./data/seed/plan-2026.json',{cache:'no-store'}).then(r=>r.json()).then(x=>{seedPlan=x;refresh();}).catch(()=>{});db.ref('lor/plans').on('value',s=>{livePlans=[];s.forEach(c=>livePlans.push({id:c.key,...(c.val()||{})}));refresh();});db.ref('lor/rounds').on('value',s=>{rounds=[];s.forEach(c=>rounds.push({id:c.key,...(c.val()||{})}));refresh();});}
function leaders(){return [...new Set(mergedRows().map(r=>r.leaderName).filter(Boolean))];}
function years(){const ys=new Set([2026,new Date().getFullYear(),...livePlans.map(x=>Number(x.year||2026)).filter(Boolean)]);return [...ys].sort((a,b)=>a-b);}
function annualStats(rows){const s={done:0,late:0,overdue:0,current:0,planned:0};rows.forEach(r=>s[planStatus(r).key]++);return s;}
function nav(){const n=document.querySelector('.nav');if(!n||n.querySelector('[data-v36-annual]'))return;const b=document.createElement('button');b.textContent='Årsplan';b.dataset.v36Annual='1';n.insertBefore(b,n.children[2]||null);}
function annualView(){const main=document.querySelector('main.main');if(!main)return;const rows=mergedRows(activeYear),st=annualStats(rows);main.innerHTML=`<section class="v36-hero"><div><span class="eyebrow">Planlegging · ${activeYear}</span><h1>Årsplan</h1><p>Ukentlig plan for lederoppfølgingsrunder – ansvarlig, tema, avdeling og status.</p></div><div class="v36-year-actions"><select data-v36-year>${years().map(y=>`<option ${y===activeYear?'selected':''}>${y}</option>`).join('')}</select><button class="secondary-action" data-v36-new-year>+ Nytt år</button><button class="primary-action" data-v36-new-plan>+ Planlegg runde</button></div></section><section class="v36-summary"><article><span>Gjennomført</span><strong>${st.done}</strong></article><article><span>Gjennomført sent</span><strong>${st.late}</strong></article><article class="danger"><span>Forfalt</span><strong>${st.overdue}</strong></article><article><span>Gjenstår</span><strong>${st.current+st.planned}</strong></article></section><section class="card panel v36-plan"><div class="v36-head"><span>Uke</span><span>Ansvarlig</span><span>Tema</span><span>Avdeling</span><span>Medleder</span><span>Status</span><span></span></div>${rows.map(r=>{const s=planStatus(r);return `<button class="v36-row ${s.key}" data-v36-edit="${esc(r.id)}" data-v36-week="${r.week}"><strong>Uke ${r.week}</strong><span>${esc(r.leaderName||'Ikke fordelt')}</span><span>${esc(r.theme||'Tema mangler')}</span><span>${esc(r.department||'Avdeling mangler')}</span><span>${esc(r.coLeaderName||'—')}</span><em class="v36-status ${s.key}">${s.label}</em><b>→</b></button>`}).join('')}</section>`;}
function dashboardCard(){const main=document.querySelector('main.main');if(!main||!document.querySelector('#v35Dashboard')||main.querySelector('#v36AnnualDash'))return;const rows=mergedRows(new Date().getFullYear()),now=isoWeek(),near=rows.filter(r=>Number(r.week)>=now.week-1&&Number(r.week)<=now.week+3).slice(0,5),over=rows.filter(r=>planStatus(r).key==='overdue').length;const sec=document.createElement('section');sec.id='v36AnnualDash';sec.className='v36-dash card panel';sec.innerHTML=`<div class="panel-head"><div><span class="eyebrow">Årsplan ${new Date().getFullYear()}</span><h2>Kommende runder</h2></div><div class="v36-dash-actions">${over?`<span class="v36-overdue">${over} forfalt</span>`:''}<button class="text-action" data-v36-annual>Åpne årsplan →</button></div></div><div class="v36-mini-grid">${near.map(r=>{const s=planStatus(r);return `<button data-v36-edit="${esc(r.id)}" data-v36-week="${r.week}"><b>Uke ${r.week}</b><strong>${esc(r.theme||'Tema mangler')}</strong><span>${esc(r.department||'')} · ${esc(r.leaderName||'Ikke fordelt')}</span><em class="v36-status ${s.key}">${s.label}</em></button>`}).join('')||'<div class="empty-state">Ingen planlagte runder i perioden.</div>'}</div>`;document.querySelector('#v35Dashboard')?.appendChild(sec);}
function planDialog(row={}){const list=mergedRows(activeYear);const known=[...new Set([...list.map(r=>r.leaderName),...leaders()].filter(Boolean))];const opts=(arr,val)=>`<option value="">Velg</option>${arr.map(x=>`<option ${x===val?'selected':''}>${esc(x)}</option>`).join('')}`;const dlg=document.createElement('dialog');dlg.open=true;dlg.className='lor-dialog v36-dialog';dlg.innerHTML=`<form data-v36-form data-id="${esc(row.source==='live'?row.id:'')}" data-week="${row.week||''}"><div class="dialog-head"><div><span class="eyebrow">Årsplan ${activeYear}</span><h2>${row.week?`Uke ${row.week}`:'Planlegg ny runde'}</h2></div><button type="button" data-v36-close>×</button></div><div class="v36-form"><label>Uke<input name="week" type="number" min="1" max="53" required value="${row.week||''}"></label><label>Ansvarlig<select name="leaderName" required>${opts(known,row.leaderName)}</select></label><label>Tema<input name="theme" required value="${esc(row.theme||'')}"></label><label>Avdeling<select name="department" required>${opts(['Renhold','Ferdigmat','Rekvisita'],row.department)}</select></label><label class="full">Inviter med / medleder<select name="coLeaderName">${opts(known.filter(x=>x!==row.leaderName),row.coLeaderName)}</select><small>Valgfritt. Personen blir registrert som medleder på den planlagte runden.</small></label></div><div class="dialog-actions"><button type="button" class="secondary-action" data-v36-close>Avbryt</button><button class="primary-action">Lagre i årsplan</button></div></form>`;document.body.appendChild(dlg);}
async function savePlan(form){const fd=new FormData(form),id=form.dataset.id||db.ref('lor/plans').push().key;const weekNo=Number(fd.get('week'));const payload={year:activeYear,week:weekNo,leaderName:String(fd.get('leaderName')||''),theme:String(fd.get('theme')||''),themeName:String(fd.get('theme')||''),department:String(fd.get('department')||''),coLeaderName:String(fd.get('coLeaderName')||''),status:'planned',updatedAt:serverTimestamp()};await db.ref(`lor/plans/${id}`).update(payload);return id;}
async function createYear(){const y=Number(prompt('Hvilket år vil du opprette årsplan for?',String(Math.max(...years())+1)));if(!y||y<2026||y>2100)return;activeYear=y;annualView();}
function refresh(){nav();dashboardCard();if(document.querySelector('main.main [data-v36-active]'))annualView();}
document.addEventListener('click',async ev=>{const a=ev.target.closest('[data-v36-annual]');if(a){ev.preventDefault();document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));a.classList.add('active');annualView();document.querySelector('main.main')?.setAttribute('data-v36-active','1');return;}const close=ev.target.closest('[data-v36-close]');if(close){close.closest('dialog')?.remove();return;}const ny=ev.target.closest('[data-v36-new-year]');if(ny){createYear();return;}const np=ev.target.closest('[data-v36-new-plan]');if(np){planDialog({});return;}const ed=ev.target.closest('[data-v36-edit]');if(ed){const row=mergedRows(activeYear).find(r=>String(r.id)===String(ed.dataset.v36Edit)||Number(r.week)===Number(ed.dataset.v36Week));if(row)planDialog(row);return;}},true);
document.addEventListener('change',ev=>{if(ev.target.matches('[data-v36-year]')){activeYear=Number(ev.target.value);annualView();}},true);
document.addEventListener('submit',async ev=>{if(!ev.target.matches('[data-v36-form]'))return;ev.preventDefault();try{await savePlan(ev.target);ev.target.closest('dialog')?.remove();annualView();}catch(err){console.error('Kunne ikke lagre årsplan',err);alert('Kunne ikke lagre årsplanen. Kontroller tilgang/regler.');}},true);
window.addEventListener('load',()=>{bind();nav();setTimeout(dashboardCard,600);setInterval(()=>{nav();dashboardCard();},1500);});
setTimeout(()=>{bind();nav();},300);
