import { db, serverTimestamp } from './firebase.js';

let seedPlan=null, legacy2026=[], livePlans=[], liveRounds=[], annualMode=false, activeYear=2026, ready=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const first=n=>String(n||'').trim().split(/\s+/)[0]||'';
function isoWeek(date=new Date()){const d=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate()));const day=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()+4-day);const y0=new Date(Date.UTC(d.getUTCFullYear(),0,1));return {year:d.getUTCFullYear(),week:Math.ceil((((d-y0)/86400000)+1)/7)};}
function endOfIsoWeek(year,week){const jan4=new Date(Date.UTC(year,0,4)),day=jan4.getUTCDay()||7,monday=new Date(jan4);monday.setUTCDate(jan4.getUTCDate()-day+1+(week-1)*7);const sunday=new Date(monday);sunday.setUTCDate(monday.getUTCDate()+6);sunday.setUTCHours(23,59,59,999);return sunday.getTime();}
function seedRows(year){if(!seedPlan||Number(seedPlan.year)!==Number(year))return[];return (seedPlan.records||[]).map((r,i)=>({id:`seed-${year}-${r.week}-${i}`,year:Number(year),week:Number(r.week),leaderName:r.ownerName||'',theme:r.themeName||'',department:r.department||'',coLeaderName:'',source:'seed'})).filter(r=>Number.isFinite(r.week)&&r.week>=1&&r.week<=53);}
function liveRows(year){return livePlans.filter(r=>Number(r.year||2026)===Number(year)&&Number.isFinite(Number(r.week))).map(r=>({...r,year:Number(r.year||2026),week:Number(r.week),leaderName:r.leaderName||r.ownerName||'',theme:r.theme||r.themeName||'',department:r.department||'',coLeaderName:r.coLeaderName||'',source:'live'}));}
function mergedRows(year=activeYear){const by=new Map(seedRows(year).map(r=>[`${year}:${r.week}`,r]));liveRows(year).forEach(r=>by.set(`${year}:${r.week}`,{...(by.get(`${year}:${r.week}`)||{}),...r}));return [...by.values()].sort((a,b)=>a.week-b.week);}
function completedFor(p){const live=liveRounds.find(r=>r.planId===p.id||(Number(r.planWeek)===Number(p.week)&&(!p.theme||r.theme===p.theme)&&(!p.department||r.department===p.department)&&(!p.leaderName||first(r.leaderName).toLowerCase()===first(p.leaderName).toLowerCase())));if(live)return {time:Number(live.completedAt||live.startedAt||0),source:'digital'};if(Number(p.year)===2026){const old=legacy2026.find(r=>Number(r.week)===Number(p.week)&&(!p.leaderName||first(r.leader).toLowerCase()===first(p.leaderName).toLowerCase()));if(old)return {time:old.date?new Date(`${old.date}T12:00:00`).getTime():0,source:'historikk'};}return null;}
function statusFor(p){const c=completedFor(p);if(c){const late=c.time&&c.time>endOfIsoWeek(Number(p.year),Number(p.week));return {key:late?'late':'done',label:late?'Gjennomført for sent':'Gjennomført'};}const now=isoWeek(),y=Number(p.year),w=Number(p.week);if(y<now.year||(y===now.year&&w<now.week))return {key:'overdue',label:'Forfalt'};if(y===now.year&&w===now.week)return {key:'current',label:'Denne uken'};return {key:'planned',label:'Planlagt'};}
function years(){return [...new Set([2026,new Date().getFullYear(),...livePlans.map(x=>Number(x.year||2026)).filter(Boolean)])].sort((a,b)=>a-b);}
function stats(rows){const out={done:0,late:0,overdue:0,current:0,planned:0};rows.forEach(r=>out[statusFor(r).key]++);return out;}
function ensureNav(){const nav=document.querySelector('.nav');if(!nav)return;let btn=nav.querySelector('[data-v362-annual]');if(!btn){btn=document.createElement('button');btn.textContent='Årsplan';btn.dataset.v362Annual='1';const ref=[...nav.children].find(x=>x.dataset.view==='findings');nav.insertBefore(btn,ref||null);}btn.classList.toggle('active',annualMode);if(annualMode)nav.querySelectorAll('button:not([data-v362-annual])').forEach(b=>b.classList.remove('active'));}
function annualSignature(){return JSON.stringify({y:activeYear,seed:!!seedPlan,p:livePlans.length,r:liveRounds.length,h:legacy2026.length,rows:mergedRows(activeYear).map(x=>[x.week,x.leaderName,x.theme,x.department,x.coLeaderName])});}
function renderAnnual(force=false){if(!annualMode)return;const main=document.querySelector('main.main');if(!main)return;ensureNav();const sig=annualSignature();if(!force&&main.dataset.v362Annual===sig)return;const rows=mergedRows(activeYear),s=stats(rows);main.className='main v362-annual-main';main.dataset.v362Annual=sig;main.innerHTML=`<section class="v36-hero"><div><span class="eyebrow">Planlegging · ${activeYear}</span><h1>Årsplan</h1><p>Ukentlig plan for lederoppfølgingsrunder – ansvarlig, tema, avdeling og status.</p></div><div class="v36-year-actions"><select data-v362-year>${years().map(y=>`<option ${y===activeYear?'selected':''}>${y}</option>`).join('')}</select><button class="secondary-action" data-v362-new-year>+ Nytt år</button><button class="primary-action" data-v362-new-plan>+ Planlegg runde</button></div></section><section class="v36-summary"><article><span>Gjennomført</span><strong>${s.done}</strong></article><article><span>Gjennomført sent</span><strong>${s.late}</strong></article><article class="danger"><span>Forfalt</span><strong>${s.overdue}</strong></article><article><span>Gjenstår</span><strong>${s.current+s.planned}</strong></article></section><section class="card panel v36-plan"><div class="v36-head"><span>Uke</span><span>Ansvarlig</span><span>Tema</span><span>Avdeling</span><span>Medleder</span><span>Status</span><span></span></div>${rows.map(r=>{const st=statusFor(r);return `<button class="v36-row ${st.key}" data-v362-edit="${esc(r.id)}" data-v362-week="${r.week}"><strong>Uke ${r.week}</strong><span>${esc(r.leaderName||'Ikke fordelt')}</span><span>${esc(r.theme||'Tema mangler')}</span><span>${esc(r.department||'Avdeling mangler')}</span><span>${esc(r.coLeaderName||'—')}</span><em class="v36-status ${st.key}">${st.label}</em><b>→</b></button>`}).join('')||'<div class="empty-state">Ingen runder planlagt for dette året.</div>'}</section>`;}
function dashboardStrip(){if(annualMode)return;const main=document.querySelector('main.main'),dash=main?.querySelector('#v35Dashboard');if(!dash)return;main.classList.add('v362-dashboard-main');const rows=mergedRows(new Date().getFullYear()),now=isoWeek();const overdue=rows.filter(r=>statusFor(r).key==='overdue');const upcoming=rows.filter(r=>['current','planned'].includes(statusFor(r).key)).sort((a,b)=>a.week-b.week).slice(0,5);const sig=JSON.stringify([overdue.map(x=>x.week),upcoming.map(x=>[x.week,x.leaderName,x.theme,x.department])]);let sec=dash.querySelector('#v362AnnualDash');if(!sec){sec=document.createElement('section');sec.id='v362AnnualDash';sec.className='v36-dash v362-dash';dash.prepend(sec);}if(sec.dataset.sig===sig)return;sec.dataset.sig=sig;sec.innerHTML=`<div class="v36-dash-head"><div><span class="eyebrow">Årsplan ${new Date().getFullYear()}</span><h2>${overdue.length?`${overdue.length} runder er forfalt`:'Kommende runder'}</h2></div><button class="text-action" data-v362-annual>Åpne årsplan →</button></div>${overdue.length?`<div class="v36-overdue-strip"><strong>⚠ ${overdue.length} forfalt</strong><span>${overdue.slice(0,5).map(r=>`Uke ${r.week} · ${esc(r.leaderName||'Ikke fordelt')} · ${esc(r.theme||'Tema mangler')}`).join('  •  ')}</span></div>`:''}<div class="v36-mini-grid">${upcoming.map(r=>{const st=statusFor(r);return `<button data-v362-edit="${esc(r.id)}" data-v362-week="${r.week}"><b>Uke ${r.week}</b><strong>${esc(r.theme||'Tema mangler')}</strong><span>${esc(r.department||'')} · ${esc(r.leaderName||'Ikke fordelt')}</span><em class="v36-status ${st.key}">${st.label}</em></button>`}).join('')||'<div class="empty-state">Ingen kommende runder.</div>'}</div>`;}
function knownLeaders(){return [...new Set(mergedRows(activeYear).map(r=>r.leaderName).filter(Boolean))];}
function dialog(row={}){const people=knownLeaders(),opts=(arr,val)=>`<option value="">Velg</option>${arr.map(x=>`<option ${x===val?'selected':''}>${esc(x)}</option>`).join('')}`,dlg=document.createElement('dialog');dlg.open=true;dlg.className='lor-dialog v36-dialog';dlg.innerHTML=`<form data-v362-form data-id="${esc(row.source==='live'?row.id:'')}"><div class="dialog-head"><div><span class="eyebrow">Årsplan ${activeYear}</span><h2>${row.week?`Uke ${row.week}`:'Planlegg runde'}</h2></div><button type="button" data-v362-close>×</button></div><div class="v36-form"><label>Uke<input name="week" type="number" min="1" max="53" required value="${row.week||''}"></label><label>Ansvarlig<select name="leaderName" required>${opts(people,row.leaderName)}</select></label><label>Tema<input name="theme" required value="${esc(row.theme||'')}"></label><label>Avdeling<select name="department" required>${opts(['Renhold','Ferdigmat','Rekvisita'],row.department)}</select></label><label class="full">Inviter med / medleder<select name="coLeaderName">${opts(people.filter(x=>x!==row.leaderName),row.coLeaderName)}</select><small>Valgfritt – registreres sammen med den planlagte runden.</small></label></div><div class="dialog-actions"><button type="button" class="secondary-action" data-v362-close>Avbryt</button><button class="primary-action">Lagre i årsplan</button></div></form>`;document.body.appendChild(dlg);}
async function save(form){const fd=new FormData(form),id=form.dataset.id||db.ref('lor/plans').push().key,theme=String(fd.get('theme')||'');await db.ref(`lor/plans/${id}`).update({year:activeYear,week:Number(fd.get('week')),leaderName:String(fd.get('leaderName')||''),theme,themeName:theme,department:String(fd.get('department')||''),coLeaderName:String(fd.get('coLeaderName')||''),status:'planned',updatedAt:serverTimestamp()});}
function sync(){if(!ready)return;ensureNav();if(annualMode)renderAnnual();else dashboardStrip();if(document.body.classList.contains('v362-analysis-loading')&&document.querySelector('#v34Analysis'))document.body.classList.remove('v362-analysis-loading');}
document.addEventListener('click',ev=>{const annual=ev.target.closest('[data-v362-annual]');if(annual){ev.preventDefault();annualMode=true;renderAnnual(true);return;}const normal=ev.target.closest('.nav [data-view]');if(normal){annualMode=false;if(normal.dataset.view==='analytics')document.body.classList.add('v362-analysis-loading');return;}const close=ev.target.closest('[data-v362-close]');if(close){close.closest('dialog')?.remove();return;}const edit=ev.target.closest('[data-v362-edit]');if(edit){const row=mergedRows(activeYear).find(r=>String(r.id)===String(edit.dataset.v362Edit)||Number(r.week)===Number(edit.dataset.v362Week));if(row)dialog(row);return;}if(ev.target.closest('[data-v362-new-plan]')){dialog({});return;}if(ev.target.closest('[data-v362-new-year]')){const y=Number(prompt('Hvilket år vil du opprette årsplan for?',String(Math.max(...years())+1)));if(y>=2026&&y<=2100){activeYear=y;renderAnnual(true);}return;}},true);
document.addEventListener('change',ev=>{if(ev.target.matches('[data-v362-year]')){activeYear=Number(ev.target.value);renderAnnual(true);}},true);
document.addEventListener('submit',async ev=>{if(!ev.target.matches('[data-v362-form]'))return;ev.preventDefault();try{await save(ev.target);ev.target.closest('dialog')?.remove();renderAnnual(true);}catch(err){console.error(err);alert('Kunne ikke lagre årsplan. Kontroller tilgang/regler.');}},true);
const app=document.querySelector('#app');if(app)new MutationObserver(()=>setTimeout(sync,0)).observe(app,{childList:true});
Promise.all([fetch('./data/seed/plan-2026.json',{cache:'no-store'}).then(r=>r.json()),fetch('./data/seed/history-2026.json',{cache:'no-store'}).then(r=>r.json())]).then(([p,h])=>{seedPlan=p;legacy2026=h.records||[];ready=true;sync();}).catch(err=>{console.error('Årsplan seed-feil',err);ready=true;sync();});
db.ref('lor/plans').on('value',s=>{livePlans=[];s.forEach(c=>livePlans.push({id:c.key,...(c.val()||{})}));sync();});
db.ref('lor/rounds').on('value',s=>{liveRounds=[];s.forEach(c=>liveRounds.push({id:c.key,...(c.val()||{})}));sync();});
window.addEventListener('load',()=>{sync();setInterval(sync,500);});
setTimeout(sync,250);
